name: Go Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.x]
        os: [ubuntu-latest]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: |
        env GOOS=linux GOARCH=${{ matrix.arch }} go build -v -o spotui-${{ matrix.arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: spotui-${{ matrix.arch }}
        path: spotui-${{ matrix.arch }}
